In [8]:
# Supress Warnings

#Use this cell to ignore the warnings.

#[Your Code]

In [9]:
# Import the numpy and pandas packages

#[Your Code]

## Task 1: Reading and Inspection

-  ### Subtask 1.1: Import and read

Import and read the movie data. Store it in a variable called `movies`.

In [1]:

#Making Sure that the csv file belong to the same directory as this file. And then using head command to read few rows.
#Else complete path of the directory can be used to read the file.
#read_csv is used to read the deimited file.

import numpy as np
import pandas as pd
movies=pd.read_csv('MovieData.csv')

-  ### Subtask 1.2: Inspect the dataframe

Inspect the dataframe's columns, shapes, variable types etc.

In [4]:
# Write your code for inspection here
movies.head()

#Find the the initial rows count for future references.

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000
10,Color,Zack Snyder,673.0,183.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,2.35,197000
11,Color,Bryan Singer,434.0,169.0,0.0,903.0,Marlon Brando,18000.0,200069408.0,Action|Adventure|Sci-Fi,...,2367.0,English,USA,PG-13,209000000.0,2006.0,10000.0,6.1,2.35,0
12,Color,Marc Forster,403.0,106.0,395.0,393.0,Mathieu Amalric,451.0,168368427.0,Action|Adventure,...,1243.0,English,UK,PG-13,200000000.0,2008.0,412.0,6.7,2.35,0
13,Color,Gore Verbinski,313.0,151.0,563.0,1000.0,Orlando Bloom,40000.0,423032628.0,Action|Adventure|Fantasy,...,1832.0,English,USA,PG-13,225000000.0,2006.0,5000.0,7.3,2.35,5000
14,Color,Gore Verbinski,450.0,150.0,563.0,1000.0,Ruth Wilson,40000.0,89289910.0,Action|Adventure|Western,...,711.0,English,USA,PG-13,215000000.0,2013.0,2000.0,6.5,2.35,48000
15,Color,Zack Snyder,733.0,143.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,2.35,118000
16,Color,Andrew Adamson,258.0,150.0,80.0,201.0,Pierfrancesco Favino,22000.0,141614023.0,Action|Adventure|Family|Fantasy,...,438.0,English,USA,PG,225000000.0,2008.0,216.0,6.6,2.35,0
17,Color,Joss Whedon,703.0,173.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,1.85,123000
18,Color,Rob Marshall,448.0,136.0,252.0,1000.0,Sam Claflin,40000.0,241063875.0,Action|Adventure|Fantasy,...,484.0,English,USA,PG-13,250000000.0,2011.0,11000.0,6.7,2.35,58000
19,Color,Barry Sonnenfeld,451.0,106.0,188.0,718.0,Michael Stuhlbarg,10000.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,...,341.0,English,USA,PG-13,225000000.0,2012.0,816.0,6.8,1.85,40000
20,Color,Peter Jackson,422.0,164.0,0.0,773.0,Adam Brown,5000.0,255108370.0,Adventure|Fantasy,...,802.0,English,New Zealand,PG-13,250000000.0,2014.0,972.0,7.5,2.35,65000
21,Color,Marc Webb,599.0,153.0,464.0,963.0,Andrew Garfield,15000.0,262030663.0,Action|Adventure|Fantasy,...,1225.0,English,USA,PG-13,230000000.0,2012.0,10000.0,7.0,2.35,56000
22,Color,Ridley Scott,343.0,156.0,0.0,738.0,William Hurt,891.0,105219735.0,Action|Adventure|Drama|History,...,546.0,English,USA,PG-13,200000000.0,2010.0,882.0,6.7,2.35,17000
23,Color,Peter Jackson,509.0,186.0,0.0,773.0,Adam Brown,5000.0,258355354.0,Adventure|Fantasy,...,951.0,English,USA,PG-13,225000000.0,2013.0,972.0,7.9,2.35,83000
24,Color,Chris Weitz,251.0,113.0,129.0,1000.0,Eva Green,16000.0,70083519.0,Adventure|Family|Fantasy,...,666.0,English,USA,PG-13,180000000.0,2007.0,6000.0,6.1,2.35,0
25,Color,Peter Jackson,446.0,201.0,0.0,84.0,Thomas Kretschmann,6000.0,218051260.0,Action|Adventure|Drama|Romance,...,2618.0,English,New Zealand,PG-13,207000000.0,2005.0,919.0,7.2,2.35,0
26,Color,James Cameron,315.0,194.0,0.0,794.0,Kate Winslet,29000.0,658672302.0,Drama|Romance,...,2528.0,English,USA,PG-13,200000000.0,1997.0,14000.0,7.7,2.35,26000
27,Color,Anthony Russo,516.0,147.0,94.0,11000.0,Scarlett Johansson,21000.0,407197282.0,Action|Adventure|Sci-Fi,...,1022.0,English,USA,PG-13,250000000.0,2016.0,19000.0,8.2,2.35,72000
28,Color,Peter Berg,377.0,131.0,532.0,627.0,Alexander Skarsgård,14000.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,...,751.0,English,USA,PG-13,209000000.0,2012.0,10000.0,5.9,2.35,44000
29,Color,Colin Trevorrow,644.0,124.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,2.00,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5013,Color,Eric Eason,28.0,79.0,3.0,42.0,Panchito Gómez,93.0,NaN,Drama|Family,...,21.0,English,USA,NaN,24000.0,2002.0,46.0,7.0,1.78,61
5014,Color,Uwe Boll,58.0,80.0,892.0,492.0,Katharine Isabelle,986.0,NaN,Action|Crime|Thriller,...,129.0,English,Canada,R,NaN,2009.0,918.0,6.3,2.35,0
5015,Black and White,Richard Linklater,61.0,100.0,0.0,0.0,Richard Linklater,5.0,1227508.0,Comedy|Drama,...,80.0,English,USA,R,23000.0,1991.0,0.0,7.1,1.37,2000
5016,Color,Joseph Mazzella,NaN,90.0,0.0,9.0,Mikaal Bates,313.0,NaN,Crime|Drama|Thriller,...,2.0,English,USA,NaN,25000.0,2015.0,25.0,4.8,NaN,33
5017,Color,Travis Legge,1.0,90.0,138.0,138.0,Suzi Lorraine,370.0,NaN,Comedy|Romance,...,3.0,English,USA,NaN,22000.0,2013.0,184.0,3.3,1.78,200
5018,Color,Alex Kendrick,5.0,120.0,589.0,4.0,Lisa Arnold,51.0,NaN,Drama,...,49.0,English,USA,NaN,20000.0,2003.0,49.0,6.9,1.85,725
5019,Color,Marcus Nispel,43.0,91.0,158.0,265.0,Brittany Curran,630.0,NaN,Horror|Mystery|Thriller,...,33.0,English,USA,R,NaN,2015.0,512.0,4.6,1.85,0
5020,NaN,Brandon Landers,NaN,143.0,8.0,8.0,Alana Kaniewski,720.0,NaN,Drama|Horror|Thriller,...,8.0,English,USA,NaN,17350.0,2011.0,19.0,3.0,NaN,33
5021,Color,Jay Duplass,51.0,85.0,157.0,10.0,Katie Aselton,830.0,192467.0,Comedy|Drama|Romance,...,71.0,English,USA,R,15000.0,2005.0,224.0,6.6,NaN,297
5022,Black and White,Jim Chuchu,6.0,60.0,0.0,4.0,Olwenya Maina,147.0,NaN,Drama,...,1.0,Swahili,Kenya,NaN,15000.0,2014.0,19.0,7.4,NaN,45
5023,Color,Daryl Wein,22.0,88.0,38.0,211.0,Heather Burns,331.0,76382.0,Romance,...,8.0,English,USA,NaN,15000.0,2009.0,212.0,6.2,2.35,324
5024,Color,Jason Trost,42.0,78.0,91.0,86.0,Jason Trost,407.0,NaN,Sci-Fi|Thriller,...,35.0,English,USA,Unrated,20000.0,2011.0,91.0,4.0,2.35,835
5025,Color,John Waters,73.0,108.0,0.0,105.0,Mink Stole,462.0,180483.0,Comedy|Crime|Horror,...,183.0,English,USA,NC-17,10000.0,1972.0,143.0,6.1,1.37,0
5026,Color,Olivier Assayas,81.0,110.0,107.0,45.0,Béatrice Dalle,576.0,136007.0,Drama|Music|Romance,...,39.0,French,France,R,4500.0,2004.0,133.0,6.9,2.35,171
5027,Color,Jafar Panahi,64.0,90.0,397.0,0.0,Nargess Mamizadeh,5.0,673780.0,Drama,...,26.0,Persian,Iran,Not Rated,10000.0,2000.0,0.0,7.5,1.85,697
5028,Black and White,Ivan Kavanagh,12.0,83.0,18.0,0.0,Michael Parle,10.0,NaN,Horror,...,1.0,English,Ireland,NaN,10000.0,2007.0,5.0,6.7,1.33,105
5029,Color,Kiyoshi Kurosawa,78.0,111.0,62.0,6.0,Anna Nakagawa,89.0,94596.0,Crime|Horror|Mystery|Thriller,...,50.0,Japanese,Japan,NaN,1000000.0,1997.0,13.0,7.4,1.85,817
5030,Color,Tadeo Garcia,NaN,84.0,5.0,12.0,Michael Cortez,21.0,NaN,Drama,...,3.0,English,USA,NaN,NaN,2004.0,20.0,6.1,NaN,22
5031,Color,Thomas L. Phillips,13.0,82.0,120.0,84.0,Joe Coffey,785.0,NaN,Comedy|Horror|Thriller,...,8.0,English,USA,NaN,200000.0,2012.0,98.0,5.4,16.00,424
5032,Color,Ash Baron-Cohen,10.0,98.0,3.0,152.0,Stanley B. Herman,789.0,NaN,Crime|Drama,...,14.0,English,USA,NaN,NaN,1995.0,194.0,6.4,NaN,20
5033,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
5034,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
5035,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
5036,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

## Task 2: Cleaning the Data

-  ### Subtask 2.1: Inspect Null values

Find out the number of Null values in all the columns and rows. Also, find the percentage of Null values in each column. Round off the percentages upto two decimal places.

In [5]:
# Write your code for column-wise null count here

#Hint : isnull returns boolean True/False for column value to be null or not, sum will add int count. 
movies.isna().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [6]:
# Write your code for row-wise null count here

#Sum of ISNull along axis 1 will give the null count row-wise. 
movies.isnull().sum(axis=1) #The first sum is for count of the null values and the second one if for adding all the values

0        0
1        0
2        0
3        0
4       14
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
        ..
5013     2
5014     2
5015     0
5016     5
5017     2
5018     2
5019     2
5020     5
5021     1
5022     4
5023     2
5024     1
5025     0
5026     0
5027     0
5028     3
5029     1
5030     5
5031     3
5032     4
5033     0
5034     1
5035     0
5036     3
5037     1
5038     4
5039     5
5040     4
5041     2
5042     0
Length: 5043, dtype: int64

In [7]:
# Write your code for column-wise null percentages here

# Sum of all nulls of column/Total count converted to percentage and rounded to 2 digits.
null_percent=movies.isna().sum().sum()*100/len(movies)
print(np.round(null_percent,2))

53.5

-  ### Subtask 2.2: Drop unecessary columns

For this assignment, you will mostly be analyzing the movies with respect to the ratings, gross collection, popularity of movies, etc. So many of the columns in this dataframe are not required. So it is advised to drop the following columns.
-  color
-  director_facebook_likes
-  actor_1_facebook_likes
-  actor_2_facebook_likes
-  actor_3_facebook_likes
-  actor_2_name
-  cast_total_facebook_likes
-  actor_3_name
-  duration
-  facenumber_in_poster
-  content_rating
-  country
-  movie_imdb_link
-  aspect_ratio
-  plot_keywords

In [32]:
# Write your code for dropping the columns here. It is advised to keep inspecting the dataframe after each set of operation
movies=movies.drop(['color','director_facebook_likes','actor_1_facebook_likes','actor_2_facebook_likes',
                    'actor_3_facebook_likes','actor_2_name','cast_total_facebook_likes','actor_3_name',
                    'duration','facenumber_in_poster','content_rating','country','movie_imdb_link',
                    'aspect_ratio','plot_keywords'],axis=1)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,NaN,NaN,NaN,NaN,7.1,0
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000
6,Sam Raimi,392.0,336530303.0,Action|Adventure|Romance,J.K. Simmons,Spider-Man 3,383056,1902.0,English,258000000.0,2007.0,6.2,0
7,Nathan Greno,324.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,Brad Garrett,Tangled,294810,387.0,English,260000000.0,2010.0,7.8,29000
8,Joss Whedon,635.0,458991599.0,Action|Adventure|Sci-Fi,Chris Hemsworth,Avengers: Age of Ultron,462669,1117.0,English,250000000.0,2015.0,7.5,118000
9,David Yates,375.0,301956980.0,Adventure|Family|Fantasy|Mystery,Alan Rickman,Harry Potter and the Half-Blood Prince,321795,973.0,English,250000000.0,2009.0,7.5,10000
10,Zack Snyder,673.0,330249062.0,Action|Adventure|Sci-Fi,Henry Cavill,Batman v Superman: Dawn of Justice,371639,3018.0,English,250000000.0,2016.0,6.9,197000
11,Bryan Singer,434.0,200069408.0,Action|Adventure|Sci-Fi,Kevin Spacey,Superman Returns,240396,2367.0,English,209000000.0,2006.0,6.1,0
12,Marc Forster,403.0,168368427.0,Action|Adventure,Giancarlo Giannini,Quantum of Solace,330784,1243.0,English,200000000.0,2008.0,6.7,0
13,Gore Verbinski,313.0,423032628.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: Dead Man's Chest,522040,1832.0,English,225000000.0,2006.0,7.3,5000
14,Gore Verbinski,450.0,89289910.0,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215000000.0,2013.0,6.5,48000
15,Zack Snyder,733.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,Man of Steel,548573,2536.0,English,225000000.0,2013.0,7.2,118000
16,Andrew Adamson,258.0,141614023.0,Action|Adventure|Family|Fantasy,Peter Dinklage,The Chronicles of Narnia: Prince Caspian,149922,438.0,English,225000000.0,2008.0,6.6,0
17,Joss Whedon,703.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220000000.0,2012.0,8.1,123000
18,Rob Marshall,448.0,241063875.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: On Stranger Tides,370704,484.0,English,250000000.0,2011.0,6.7,58000
19,Barry Sonnenfeld,451.0,179020854.0,Action|Adventure|Comedy|Family|Fantasy|Sci-Fi,Will Smith,Men in Black 3,268154,341.0,English,225000000.0,2012.0,6.8,40000
20,Peter Jackson,422.0,255108370.0,Adventure|Fantasy,Aidan Turner,The Hobbit: The Battle of the Five Armies,354228,802.0,English,250000000.0,2014.0,7.5,65000
21,Marc Webb,599.0,262030663.0,Action|Adventure|Fantasy,Emma Stone,The Amazing Spider-Man,451803,1225.0,English,230000000.0,2012.0,7.0,56000
22,Ridley Scott,343.0,105219735.0,Action|Adventure|Drama|History,Mark Addy,Robin Hood,211765,546.0,English,200000000.0,2010.0,6.7,17000
23,Peter Jackson,509.0,258355354.0,Adventure|Fantasy,Aidan Turner,The Hobbit: The Desolation of Smaug,483540,951.0,English,225000000.0,2013.0,7.9,83000
24,Chris Weitz,251.0,70083519.0,Adventure|Family|Fantasy,Christopher Lee,The Golden Compass,149019,666.0,English,180000000.0,2007.0,6.1,0
25,Peter Jackson,446.0,218051260.0,Action|Adventure|Drama|Romance,Naomi Watts,King Kong,316018,2618.0,English,207000000.0,2005.0,7.2,0
26,James Cameron,315.0,658672302.0,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200000000.0,1997.0,7.7,26000
27,Anthony Russo,516.0,407197282.0,Action|Adventure|Sci-Fi,Robert Downey Jr.,Captain America: Civil War,272670,1022.0,English,250000000.0,2016.0,8.2,72000
28,Peter Berg,377.0,65173160.0,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209000000.0,2012.0,5.9,44000
29,Colin Trevorrow,644.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150000000.0,2015.0,7.0,150000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,John Woo,237.0,215397307.0,Action|Adventure|Thriller,Tom Cruise,Mission: Impossible II,242188,1426.0,English,125000000.0,2000.0,6.1,0
221,Wolfgang Petersen,231.0,182618434.0,Action|Adventure|Drama|Thriller,Karen Allen,The Perfect Storm,133076,779.0,English,140000000.0,2000.0,6.4,0
222,Tim Story,262.0,131920333.0,Action|Adventure|Sci-Fi|Thriller,Chris Evans,Fantastic 4: Rise of the Silver Surfer,213275,436.0,English,130000000.0,2007.0,5.6,0
223,Ang Lee,552.0,124976634.0,Adventure|Drama|Fantasy,Suraj Sharma,Life of Pi,440084,755.0,English,120000000.0,2012.0,8.0,122000
224,Mark Steven Johnson,276.0,115802596.0,Action|Fantasy|Thriller,Nicolas Cage,Ghost Rider,182661,681.0,English,110000000.0,2007.0,5.2,0
225,Paul Greengrass,267.0,108521835.0,Action|Thriller,Matt Damon,Jason Bourne,40123,297.0,English,120000000.0,2016.0,7.1,31000
226,McG,102.0,100685880.0,Action|Adventure|Comedy|Crime,Demi Moore,Charlie's Angels: Full Throttle,100821,554.0,English,120000000.0,2003.0,4.8,0
227,Ridley Scott,775.0,126464904.0,Adventure|Mystery|Sci-Fi,Michael Fassbender,Prometheus,456260,2326.0,English,130000000.0,2012.0,7.0,97000
228,Rob Minkoff,71.0,64736114.0,Adventure|Animation|Comedy|Family|Fantasy,Nathan Lane,Stuart Little 2,36471,69.0,English,120000000.0,2002.0,5.4,459
229,Neill Blomkamp,476.0,93050117.0,Action|Drama|Sci-Fi|Thriller,Matt Damon,Elysium,338087,814.0,English,115000000.0,2013.0,6.6,61000
230,David Twohy,207.0,57637485.0,Action|Adventure|Sci-Fi|Thriller,Vin Diesel,The Chronicles of Riddick,183909,666.0,English,105000000.0,2004.0,6.7,0
231,José Padilha,492.0,58607007.0,Action|Crime|Sci-Fi|Thriller,Gary Oldman,RoboCop,182899,630.0,English,100000000.0,2014.0,6.2,60000
232,Lana Wachowski,284.0,43929341.0,Action|Family|Sport,Scott Porter,Speed Racer,57873,414.0,English,120000000.0,2008.0,6.1,0
233,James L. Brooks,168.0,30212620.0,Comedy|Drama|Romance,Shelley Conn,How Do You Know,35066,196.0,English,120000000.0,2010.0,5.3,0
234,James Mangold,283.0,76418654.0,Action|Comedy|Romance,Tom Cruise,Knight and Day,148280,348.0,English,117000000.0,2010.0,6.3,11000
235,Joseph Kosinski,539.0,89021735.0,Action|Adventure|Mystery|Sci-Fi,Morgan Freeman,Oblivion,387436,892.0,English,120000000.0,2013.0,7.0,71000
236,George Lucas,359.0,380262555.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode III - Revenge of the Sith,520104,3286.0,English,113000000.0,2005.0,7.6,10000
237,George Lucas,284.0,310675583.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode II - Attack of the Clones,464310,3516.0,English,115000000.0,2002.0,6.7,0
238,Pete Docter,250.0,289907418.0,Adventure|Animation|Comedy|Family|Fantasy,Steve Buscemi,"Monsters, Inc.",585659,593.0,English,115000000.0,2001.0,8.1,0
239,James Mangold,440.0,132550960.0,Action|Adventure|Sci-Fi|Thriller,Hugh Jackman,The Wolverine,328067,533.0,English,120000000.0,2013.0,6.7,68000
240,George Lucas,320.0,474544677.0,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115000000.0,1999.0,6.5,13000
241,Kirk De Micco,257.0,187165546.0,Adventure|Animation|Comedy|Family|Fantasy,Ryan Reynolds,The Croods,150618,195.0,English,135000000.0,2013.0,7.3,28000
242,Frédéric Forestier,33.0,NaN,Adventure|Comedy|Family|Fantasy,Alain Delon,Asterix at the Olympic Games,20567,36.0,French,78000000.0,2008.0,5.1,291
243,John Woo,152.0,40911830.0,Action|Drama|War,Nicolas Cage,Windtalkers,55994,454.0,English,115000000.0,2002.0,6.0,0
244,Cedric Nicolas-Troyan,231.0,47952020.0,Action|Adventure|Drama|Fantasy,Chris Hemsworth,The Huntsman: Winter's War,37750,134.0,English,115000000.0,2016.0,6.1,16000
245,Jonathan Liebesman,348.0,190871240.0,Action|Adventure|Comedy|Sci-Fi,Noel Fisher,Teenage Mutant Ninja Turtles,167085,491.0,English,125000000.0,2014.0,5.9,62000
246,Alfonso Cuarón,738.0,274084951.0,Adventure|Drama|Sci-Fi|Thriller,Phaldut Sharma,Gravity,582917,1885.0,English,100000000.0,2013.0,7.8,147000
247,Roger Donaldson,93.0,67155742.0,Action|Adventure|Thriller,Jamie Renée Smith,Dante's Peak,62271,277.0,English,116000000.0,1997.0,5.8,0
248,Dave Green,181.0,81638674.0,Action|Adventure|Comedy|Sci-Fi,Stephen Amell,Teenage Mutant Ninja Turtles: Out of the Shadows,17533,115.0,English,135000000.0,2016.0,6.3,12000
249,Josh Trank,369.0,56114221.0,Action|Adventure|Sci-Fi,Tim Blake Nelson,Fantastic Four,110486,695.0,English,120000000.0,2015.0,4.3,41000

-  ### Subtask 2.3: Drop unecessary rows using columns with high Null percentages

Now, on inspection you might notice that some columns have large percentage (greater than 5%) of Null values. Drop all the rows which have Null values for such columns.

In [35]:
# Write your code for dropping the rows here

round(100*(movies.isnull().sum()/len(movies.index)),2)
#movies=movies[~np.isnan(movies['gross'])]
#movies=movies[~np.isnan(movies['budget'])]
#movies.head(10)

director_name             0.00
num_critic_for_reviews    0.03
gross                     0.00
genres                    0.00
actor_1_name              0.08
movie_title               0.00
num_voted_users           0.00
num_user_for_reviews      0.00
language                  0.08
budget                    0.00
title_year                0.00
imdb_score                0.00
movie_facebook_likes      0.00
dtype: float64

-  ### Subtask 2.4: Drop unecessary rows

Some of the rows might have greater than five NaN values. Such rows aren't of much use for the analysis and hence, should be removed.

In [36]:
# Write your code for dropping the rows here

#Dropping rows with more than 5 NaN values. thresh is kept 5.
movies=movies.dropna(thresh=5, axis=0)
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000

-  ### Subtask 2.5: Fill NaN values

You might notice that the `language` column has some NaN values. Here, on inspection, you will see that it is safe to replace all the missing values with `'English'`.

In [37]:
# Write your code for filling the NaN values in the 'language' column here
movies['language']= 'English'
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237000000.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300000000.0,2007.0,7.1,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245000000.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250000000.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263700000.0,2012.0,6.6,24000

-  ### Subtask 2.6: Check the number of retained rows

You might notice that two of the columns viz. `num_critic_for_reviews` and `actor_1_name` have small percentages of NaN values left. You can let these columns as it is for now. Check the number and percentage of the rows retained after completing all the tasks above.

In [39]:
# Write your code for checking number of retained rows here
#[Your Code]
movies.shape
100*len(movies.index)/5043 
round(77.15645449137418)

77

**Checkpoint 1:** You might have noticed that we still have around `77%` of the rows!

## Task 3: Data Analysis

-  ### Subtask 3.1: Change the unit of columns

Convert the unit of the `budget` and `gross` columns from `$` to `million $`.

In [40]:
# Write your code for unit conversion here
 
#Changing the value of each value of budget and gross by dividing by 1000000 using apply function.
#[Your Code]
movies['gross']=movies['gross']/1000000
movies['budget']=movies['budget']/1000000
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7,2012.0,6.6,24000

-  ### Subtask 3.2: Find the movies with highest profit

    1. Create a new column called `profit` which contains the difference of the two columns: `gross` and `budget`.
    2. Sort the dataframe using the `profit` column as reference.
    3. Extract the top ten profiting movies in descending order and store them in a new dataframe - `top10`

In [41]:
# Write your code for creating the profit column here
movies['profit']=(movies['gross']-movies['budget'])
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0,9.404152
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000,-44.925825
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000,198.130642
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7,2012.0,6.6,24000,-190.641321

In [42]:
# Write your code for sorting the dataframe here
movies.sort_values(by='profit', ascending=False)

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.000000,2009.0,7.9,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic World,418214,1290.0,English,150.000000,2015.0,7.0,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,Titanic,793059,2528.0,English,200.000000,1997.0,7.7,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New Hope,911097,1470.0,English,11.000000,1977.0,8.7,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-Terrestrial,281842,515.0,English,10.500000,1982.0,7.9,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.000000,2012.0,8.1,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The Avengers,995415,1722.0,English,220.000000,2012.0,8.1,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion King,644348,656.0,English,45.000000,1994.0,8.5,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom Menace,534658,3597.0,English,115.000000,1999.0,6.5,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark Knight,1676169,4667.0,English,185.000000,2008.0,9.0,37000,348.316061
439,Gary Ross,673.0,407.999255,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games,701607,1959.0,English,78.000000,2012.0,7.3,140000,329.999255
812,Tim Miller,579.0,363.024263,Action|Adventure|Comedy|Romance|Sci-Fi,Ryan Reynolds,Deadpool,479047,1058.0,English,58.000000,2016.0,8.1,117000,305.024263
186,Francis Lawrence,502.0,424.645577,Adventure|Sci-Fi|Thriller,Jennifer Lawrence,The Hunger Games: Catching Fire,498397,706.0,English,130.000000,2013.0,7.6,82000,294.645577
697,Steven Spielberg,308.0,356.784000,Adventure|Sci-Fi|Thriller,Wayne Knight,Jurassic Park,613473,895.0,English,63.000000,1993.0,8.1,19000,293.784000
521,Pierre Coffin,306.0,368.049635,Animation|Comedy|Family|Sci-Fi,Steve Carell,Despicable Me 2,286877,284.0,English,76.000000,2013.0,7.5,56000,292.049635
814,Clint Eastwood,490.0,350.123553,Action|Biography|Drama|History|Thriller|War,Bradley Cooper,American Sniper,325264,916.0,English,58.800000,2014.0,7.3,112000,291.323553
338,Andrew Stanton,301.0,380.838870,Adventure|Animation|Comedy|Family,Alexander Gould,Finding Nemo,692482,866.0,English,94.000000,2003.0,8.2,11000,286.838870
582,Andrew Adamson,205.0,436.471036,Adventure|Animation|Comedy|Family|Fantasy|Romance,Rupert Everett,Shrek 2,314630,483.0,English,150.000000,2004.0,7.2,0,286.471036
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the King,1215718,3189.0,English,94.000000,2003.0,8.9,16000,283.019252
1536,Richard Marquand,197.0,309.125409,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode VI - Return of the Jedi,681857,647.0,English,32.500000,1983.0,8.4,14000,276.625409
836,Robert Zemeckis,149.0,329.691196,Comedy|Drama,Tom Hanks,Forrest Gump,1251222,1398.0,English,55.000000,1994.0,8.8,59000,274.691196
2051,Irvin Kershner,223.0,290.158751,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode V - The Empire Strikes Back,837759,900.0,English,18.000000,1980.0,8.8,17000,272.158751
2601,Chris Columbus,102.0,285.761243,Comedy|Family,Macaulay Culkin,Home Alone,311075,305.0,English,18.000000,1990.0,7.5,20000,267.761243
236,George Lucas,359.0,380.262555,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode III - Revenge of the Sith,520104,3286.0,English,113.000000,2005.0,7.6,10000,267.262555
161,Sam Raimi,291.0,403.706375,Action|Adventure|Fantasy|Romance,J.K. Simmons,Spider-Man,544665,2012.0,English,139.000000,2002.0,7.3,5000,264.706375
563,Kyle Balda,308.0,336.029560,Action|Animation|Comedy|Family|Sci-Fi,Steve Carell,Minions,142403,275.0,English,74.000000,2015.0,6.4,70000,262.029560
1181,M. Night Shyamalan,234.0,293.501675,Drama|Mystery|Thriller,Bruce Willis,The Sixth Sense,704766,2073.0,English,40.000000,1999.0,8.1,14000,253.501675
2917,Steven Spielberg,385.0,260.000000,Adventure|Drama|Thriller,Roy Scheider,Jaws,412454,962.0,English,8.000000,1975.0,8.0,21000,252.000000
125,Chris Buck,406.0,400.736600,Adventure|Animation|Comedy|Family|Fantasy|Musical,Josh Gad,Frozen,421658,904.0,English,150.000000,2013.0,7.6,58000,250.736600
519,Yarrow Cheney,165.0,323.505540,Animation|Comedy|Family,Steve Coogan,The Secret Life of Pets,24407,155.0,English,75.000000,2016.0,6.8,36000,248.505540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3879,Joe Wright,256.0,34.964818,Adventure|Family|Fantasy,Hugh Jackman,Pan,39975,186.0,English,150.000000,2015.0,5.8,24000,-115.035182
145,Joe Wright,256.0,34.964818,Adventure|Family|Fantasy,Hugh Jackman,Pan,39956,186.0,English,150.000000,2015.0,5.8,24000,-115.035182
303,Joe Wright,256.0,34.964818,Adventure|Family|Fantasy,Hugh Jackman,Pan,39956,186.0,English,150.000000,2015.0,5.8,24000,-115.035182
113,Oliver Stone,248.0,34.293771,Action|Adventure|Biography|Drama|History|Roman...,Anthony Hopkins,Alexander,138863,1390.0,English,155.000000,2004.0,5.5,0,-120.706229
14,Gore Verbinski,450.0,89.289910,Action|Adventure|Western,Johnny Depp,The Lone Ranger,181792,711.0,English,215.000000,2013.0,6.5,48000,-125.710090
143,Simon Wells,132.0,21.379315,Action|Adventure|Animation|Comedy|Family|Sci-Fi,Elisabeth Harnois,Mars Needs Moms,17590,112.0,English,150.000000,2011.0,5.4,0,-128.620685
62,Lana Wachowski,384.0,47.375327,Action|Adventure|Sci-Fi,Channing Tatum,Jupiter Ascending,139593,720.0,English,176.000000,2015.0,5.4,44000,-128.624673
49,Bryan Singer,338.0,65.171860,Adventure|Fantasy,Eddie Marsan,Jack the Giant Slayer,106416,205.0,English,195.000000,2013.0,6.3,22000,-129.828140
85,Carl Rinsch,218.0,38.297305,Action|Adventure|Drama|Fantasy,Keanu Reeves,47 Ronin,116994,324.0,English,175.000000,2013.0,6.3,35000,-136.702695
2339,Jean-Marie Poiré,8.0,0.146072,Comedy|Family|Fantasy|Sci-Fi,Christian Clavier,Les couloirs du temps: Les visiteurs II,7147,16.0,English,140.000000,1998.0,6.0,136,-139.853928
28,Peter Berg,377.0,65.173160,Action|Adventure|Sci-Fi|Thriller,Liam Neeson,Battleship,202382,751.0,English,209.000000,2012.0,5.9,44000,-143.826840
1782,Jacques Perrin,100.0,10.762178,Documentary,Jacques Perrin,Winged Migration,10369,153.0,English,160.000000,2001.0,8.0,1000,-149.237822
3877,R. Balki,12.0,0.199228,Comedy|Drama,Vidya Balan,Paa,7295,49.0,English,150.000000,2009.0,7.2,504,-149.800772
91,Robert Zemeckis,188.0,0.665426,Adventure|Animation|Family|Fantasy,Tom Hanks,The Polar Express,120798,444.0,English,165.000000,2004.0,6.6,10000,-164.334574
3659,Prachya Pinkaew,112.0,11.905519,Action|Crime|Drama|Thriller,Jon Foo,The Protector,30210,214.0,English,200.000000,2005.0,7.1,0,-188.094481
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.700000,2012.0,6.6,24000,-190.641321
2740,Tony Jaa,110.0,0.102055,Action,Nirut Sirichanya,Ong-bak 2,24570,72.0,English,300.000000,2008.0,6.2,0,-299.897945
1016,Luc Besson,111.0,14.131298,Adventure|Biography|Drama|History|War,Paul Brooke,The Messenger: The Story of Joan of Arc,55889,390.0,English,390.000000,1999.0,6.4,0,-375.868702
3311,Chatrichalerm Yukol,31.0,0.454255,Action|Adventure|Drama|History|War,Sarunyu Wongkrachang,The Legend of Suriyothai,1666,47.0,English,400.000000,2001.0,6.6,124,-399.545745
1338,John Woo,160.0,0.626809,Action|Adventure|Drama|History|War,Takeshi Kaneshiro,Red Cliff,36894,105.0,English,553.632000,2008.0,7.4,0,-553.005191
3273,Anurag Basu,41.0,1.602466,Action|Drama|Romance|Thriller,Bárbara Mori,Kites,9673,106.0,English,600.000000,2010.0,6.0,0,-598.397534
3075,Karan Johar,20.0,3.275443,Drama,Shah Rukh Khan,Kabhi Alvida Naa Kehna,13998,264.0,English,700.000000,2006.0,6.0,659,-696.724557
3851,Carlos Saura,35.0,1.687311,Drama|Musical,Mía Maestro,Tango,2412,40.0,English,700.000000,1998.0,7.2,539,-698.312689
4542,Takao Okawara,107.0,10.037390,Action|Adventure|Drama|Sci-Fi|Thriller,Hiroshi Abe,Godzilla 2000,5442,140.0,English,1000.000000,1999.0,6.0,339,-989.962610
3423,Katsuhiro Ôtomo,150.0,0.439162,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,106160,430.0,English,1100.000000,1988.0,8.1,0,-1099.560838
2334,Katsuhiro Ôtomo,105.0,0.410388,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,13727,79.0,English,2127.519898,2004.0,6.9,973,-2127.109510
2323,Hayao Miyazaki,174.0,2.298191,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,221552,570.0,English,2400.000000,1997.0,8.4,11000,-2397.701809
3005,Lajos Koltai,73.0,0.195888,Drama|Romance|War,Marcell Nagy,Fateless,5603,45.0,English,2500.000000,2005.0,7.1,607,-2499.804112
3859,Chan-wook Park,202.0,0.211667,Crime|Drama,Min-sik Choi,Lady Vengeance,53508,131.0,English,4200.000000,2005.0,7.7,4000,-4199.788333
2988,Joon-ho Bong,363.0,2.201412,Comedy|Drama|Horror|Sci-Fi,Doona Bae,The Host,68883,279.0,English,12215.500000,2006.0,7.0,7000,-12213.298588

In [43]:
data= movies.sort_values(by='profit', ascending=False)
top10= pd.DataFrame(data, columns=['profit'])
top10.head(10)

          profit
0     523.505847
29    502.177271
26    458.672302
3024  449.935665
3080  424.449459
794   403.279547
17    403.279547
509   377.783777
240   359.544677
66    348.316061

-  ### Subtask 3.3: Drop duplicate values

After you found out the top 10 profiting movies, you might have notice a duplicate value. So, it seems like the dataframe has duplicate values as well. Drop the duplicate values from the dataframe and repeat `Subtask 3.2`.

In [44]:
# Write your code for dropping duplicate values here
top10.drop_duplicates(subset=None,keep='first',inplace=False).head(10)

          profit
0     523.505847
29    502.177271
26    458.672302
3024  449.935665
3080  424.449459
794   403.279547
509   377.783777
240   359.544677
66    348.316061
439   329.999255

In [45]:
# Write code for repeating subtask 2 here

#Sort df by profit in descending order.Print Top 10 movies for verification.
data= movies.sort_values(by='profit', ascending=False)
top10= pd.DataFrame(data, columns=['profit'])
top10.head(10)

          profit
0     523.505847
29    502.177271
26    458.672302
3024  449.935665
3080  424.449459
794   403.279547
17    403.279547
509   377.783777
240   359.544677
66    348.316061

**Checkpoint 2:** You might spot two movies directed by `James Cameron` in the list.

-  ### Subtask 3.4: Find IMDb Top 250

    1. Create a new dataframe `IMDb_Top_250` and store the top 250 movies with the highest IMDb Rating (corresponding to the column: `imdb_score`). Also make sure that for all of these movies, the `num_voted_users` is greater than 25,000.
Also add a `Rank` column containing the values 1 to 250 indicating the ranks of the corresponding films.
    2. Extract all the movies in the `IMDb_Top_250` dataframe which are not in the English language and store them in a new dataframe named `Top_Foreign_Lang_Film`.

In [46]:
# Write your code for extracting the top 250 movies as per the IMDb score here. Make sure that you store it in a new dataframe 
# and name that dataframe as 'IMDb_Top_250'
data= movies.sort_values(by='imdb_score', ascending=False)
IMDB_Top_250= pd.DataFrame(data, columns=['movie_title','imdb_score'])
IMDB_Top_250.head(250)

                                            movie_title  imdb_score
1937                          The Shawshank Redemption          9.3
3466                                     The Godfather          9.2
66                                     The Dark Knight          9.0
2837                            The Godfather: Part II          9.0
3355                                      Pulp Fiction          8.9
1874                                  Schindler's List          8.9
4498                    The Good, the Bad and the Ugly          8.9
339      The Lord of the Rings: The Return of the King          8.9
97                                           Inception          8.8
270   The Lord of the Rings: The Fellowship of the R...         8.8
836                                       Forrest Gump          8.8
2051    Star Wars: Episode V - The Empire Strikes Back          8.8
683                                         Fight Club          8.8
654                                         The Matrix          8.7
4029                                       City of God          8.7
4747                                     Seven Samurai          8.7
340              The Lord of the Rings: The Two Towers          8.7
3867                   One Flew Over the Cuckoo's Nest          8.7
3024                Star Wars: Episode IV - A New Hope          8.7
1903                                        Goodfellas          8.7
3592                                The Usual Suspects          8.6
1600                                             Se7en          8.6
2373                                     Spirited Away          8.6
648                                Saving Private Ryan          8.6
96                                        Interstellar          8.6
2158                          The Silence of the Lambs          8.6
3175                                American History X          8.6
4427                                      Modern Times          8.6
1233                                      The Prestige          8.5
2363                                Back to the Future          8.5
...                                                 ...         ...
706                                  The Hateful Eight          7.9
2919                                Ernest & Celestine          7.9
639                                        The Insider          7.9
1171                                              Hero          7.9
3768                                              Moon          7.9
3680                                Do the Right Thing          7.9
3193                                             Crash          7.9
3080                        E.T. the Extra-Terrestrial          7.9
3264                                             Amour          7.9
4499                                 The Second Mother          7.9
353                                        Toy Story 2          7.9
3357                                      Nightcrawler          7.9
3361                              Little Miss Sunshine          7.9
3452                                             Crash          7.9
3029                                       The Fighter          7.9
4415                                       Nine Queens          7.9
3510                                        Veer-Zaara          7.9
845                                   Captain Phillips          7.9
3595                                      The Wrestler          7.9
3677                                        The Chorus          7.9
788                                      Almost Famous          7.9
927                                              Shrek          7.9
0                                               Avatar          7.9
1813                                   The Right Stuff          7.9
1871                                             Taken          7.9
1606                                      The Notebook          7.9
89                                          Big Hero 6          7.9
1884                                  The Untouchables          7.9
1748                            Straight Outta Compton          7.9
99                   The Hobbit: An Unexpected Journey          7.9

[250 rows x 2 columns]

In [47]:
#Taking rows whoes language column value is not En

data= movies.loc[(movies['language']!= 'English'),]
#Top_Foreign_Lang_Film=pd.dataframe(data, columns=['foreign_language'])
#Top_Foreign_Lang_Film.head(250)

**Checkpoint 3:** Can you spot `Veer-Zaara` in the dataframe?

- ### Subtask 3.5: Find the best directors

    1. Group the dataframe using the `director_name` column.
    2. Find out the top 10 directors for whom the mean of `imdb_score` is the highest and store them in a new dataframe `top10director`.

In [48]:
#Write your code for extracting the top 10 directors here
movies['mean_imdb_score']=movies['imdb_score'].mean()
data= movies.sort_values(by='mean_imdb_score', ascending=False)
top10director= pd.DataFrame(data, columns=['director_name','imdb_score','mean_imdb_score'])
top10director.head(10)

                 director_name  imdb_score  mean_imdb_score
0                James Cameron         7.9         6.463506
2888            Mark Neveldine         4.5         6.463506
2859               Spike Jonze         7.8         6.463506
2860                Mark Brown         6.1         6.463506
2861                Dave Green         5.8         6.463506
2862            John Stockwell         6.5         6.463506
2863            Clint Eastwood         7.9         6.463506
2864            Michael Polish         6.3         6.463506
2865  Daisy von Scherler Mayer         3.8         6.463506
2866          Lenny Abrahamson         8.3         6.463506

**Checkpoint 4:** No surprises that `Damien Chazelle` (director of Whiplash and La La Land) is in this list.

-  ### Subtask 3.6: Find popular genres

You might have noticed the `genres` column in the dataframe with all the genres of the movies seperated by a pipe (`|`). Out of all the movie genres, the first two are most significant for any film.

1. Extract the first two genres from the `genres` column and store them in two new columns: `genre_1` and `genre_2`. Some of the movies might have only one genre. In such cases, extract the single genre into both the columns, i.e. for such movies the `genre_2` will be the same as `genre_1`.
2. Group the dataframe using `genre_1` as the primary column and `genre_2` as the secondary column.
3. Find out the 5 most popular combo of genres by finding the mean of the gross values using the `gross` column and store them in a new dataframe named `PopGenre`.

In [49]:
# Write your code for extracting the first two genres of each movie here
#[Your Code]
movies[['genre_1', 'genre_2']]= movies['genres'].str.split('|', n=1, expand=True)
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,mean_imdb_score,genre_1,genre_2
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847,6.463506,Action,Adventure|Fantasy|Sci-Fi
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0,9.404152,6.463506,Action,Adventure|Fantasy
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000,-44.925825,6.463506,Action,Adventure|Thriller
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000,198.130642,6.463506,Action,Thriller
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7,2012.0,6.6,24000,-190.641321,6.463506,Action,Adventure|Sci-Fi

In [50]:
#Movies has been grouped by genre_1 and then genre_2
grouped=movies.groupby(movies.genre_1)
movies=grouped.get_group("Action")
movies.head()

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,mean_imdb_score,genre_1,genre_2
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847,6.463506,Action,Adventure|Fantasy|Sci-Fi
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0,9.404152,6.463506,Action,Adventure|Fantasy
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000,-44.925825,6.463506,Action,Adventure|Thriller
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000,198.130642,6.463506,Action,Thriller
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7,2012.0,6.6,24000,-190.641321,6.463506,Action,Adventure|Sci-Fi

In [51]:
#Pivot table can be used to calculate the mean gross and then group by genres. And then sorted by the gross value.
movies['mean_gross']=movies['gross'].mean()
data= movies.sort_values(by='mean_gross', ascending=False)
PopGenre= pd.DataFrame(data, columns=['gross','mean_gross'])
movies.head(5)

C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,num_user_for_reviews,language,budget,title_year,imdb_score,movie_facebook_likes,profit,mean_imdb_score,genre_1,genre_2,mean_gross
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,3054.0,English,237.0,2009.0,7.9,33000,523.505847,6.463506,Action,Adventure|Fantasy|Sci-Fi,77.142868
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,1238.0,English,300.0,2007.0,7.1,0,9.404152,6.463506,Action,Adventure|Fantasy,77.142868
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,994.0,English,245.0,2015.0,6.8,85000,-44.925825,6.463506,Action,Adventure|Thriller,77.142868
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,2701.0,English,250.0,2012.0,8.5,164000,198.130642,6.463506,Action,Thriller,77.142868
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,738.0,English,263.7,2012.0,6.6,24000,-190.641321,6.463506,Action,Adventure|Sci-Fi,77.142868

**Checkpoint 5:** Well, as it turns out. `Family + Sci-Fi` is the most popular combo of genres out there!

-  ### Subtask 3.7: Find the critic-favorite and audience-favorite actors

    1. Create three new dataframes namely, `Meryl_Streep`, `Leo_Caprio`, and `Brad_Pitt` which contain the movies in which the actors: 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' are the lead actors. Use only the `actor_1_name` column for extraction. Also, make sure that you use the names 'Meryl Streep', 'Leonardo DiCaprio', and 'Brad Pitt' for the said extraction.
    2. Append the rows of all these dataframes and store them in a new dataframe named `Combined`.
    3. Group the combined dataframe using the `actor_1_name` column.
    4. Find the mean of the `num_critic_for_reviews` and `num_user_for_review` and identify the actors which have the highest mean.

In [52]:
# Write your code for creating three new dataframes here
Meryl_Streep=movies[['actor_1_name','movie_title','num_critic_for_reviews','num_user_for_reviews']]
Leo_Caprio=movies[['actor_1_name','movie_title','num_critic_for_reviews','num_user_for_reviews']]
Brad_Pitt=movies[['actor_1_name','movie_title','num_critic_for_reviews','num_user_for_reviews']]

In [53]:
#Using loc function to check if the actor name contains Leonardo DiCaprio, including only those rows.
Leo_Caprio=Leo_Caprio.loc[Leo_Caprio['actor_1_name']=='Leonardo DiCaprio',:]
Leo_Caprio.head()

,actor_1_name,movie_title,num_critic_for_reviews,num_user_for_reviews
97,Leonardo DiCaprio,Inception,642.0,2803.0
641,Leonardo DiCaprio,Body of Lies,238.0,263.0
1422,Leonardo DiCaprio,The Man in the Iron Mask,83.0,244.0
1560,Leonardo DiCaprio,The Quick and the Dead,63.0,216.0

In [54]:
#Using loc function to check if the actor name contains Brad Pitt, including only those rows.
#[Your Code]
Brad_Pitt=Brad_Pitt.loc[Brad_Pitt['actor_1_name']=='Brad Pitt',:]
Brad_Pitt.head()

,actor_1_name,movie_title,num_critic_for_reviews,num_user_for_reviews
255,Brad Pitt,Mr. & Mrs. Smith,233.0,798.0
382,Brad Pitt,Spy Game,142.0,361.0
470,Brad Pitt,Fury,406.0,701.0
2898,Brad Pitt,True Romance,122.0,460.0

In [55]:
# Write your code for combining the three dataframes here

Combined=Meryl_Streep.append(Leo_Caprio).append(Brad_Pitt)

Combined

,actor_1_name,movie_title,num_critic_for_reviews,num_user_for_reviews
0,CCH Pounder,Avatar,723.0,3054.0
1,Johnny Depp,Pirates of the Caribbean: At World's End,302.0,1238.0
2,Christoph Waltz,Spectre,602.0,994.0
3,Tom Hardy,The Dark Knight Rises,813.0,2701.0
5,Daryl Sabara,John Carter,462.0,738.0
6,J.K. Simmons,Spider-Man 3,392.0,1902.0
8,Chris Hemsworth,Avengers: Age of Ultron,635.0,1117.0
10,Henry Cavill,Batman v Superman: Dawn of Justice,673.0,3018.0
11,Kevin Spacey,Superman Returns,434.0,2367.0
12,Giancarlo Giannini,Quantum of Solace,403.0,1243.0
13,Johnny Depp,Pirates of the Caribbean: Dead Man's Chest,313.0,1832.0
14,Johnny Depp,The Lone Ranger,450.0,711.0
15,Henry Cavill,Man of Steel,733.0,2536.0
16,Peter Dinklage,The Chronicles of Narnia: Prince Caspian,258.0,438.0
17,Chris Hemsworth,The Avengers,703.0,1722.0
18,Johnny Depp,Pirates of the Caribbean: On Stranger Tides,448.0,484.0
19,Will Smith,Men in Black 3,451.0,341.0
21,Emma Stone,The Amazing Spider-Man,599.0,1225.0
22,Mark Addy,Robin Hood,343.0,546.0
25,Naomi Watts,King Kong,446.0,2618.0
27,Robert Downey Jr.,Captain America: Civil War,516.0,1022.0
28,Liam Neeson,Battleship,377.0,751.0
29,Bryce Dallas Howard,Jurassic World,644.0,1290.0
30,Albert Finney,Skyfall,750.0,1498.0
31,J.K. Simmons,Spider-Man 2,300.0,1303.0
32,Robert Downey Jr.,Iron Man 3,608.0,1187.0
34,Hugh Jackman,X-Men: The Last Stand,334.0,1912.0
36,Glenn Morshower,Transformers: Revenge of the Fallen,366.0,1439.0
37,Bingbing Li,Transformers: Age of Extinction,378.0,918.0
39,Emma Stone,The Amazing Spider-Man 2,495.0,1067.0
...,...,...,...,...
4403,Bolo Yeung,Bloodsport,61.0,210.0
4446,Tom Cruise,Jack Reacher,387.0,448.0
4466,Bruce Willis,Mercury Rising,79.0,127.0
4518,Terry Kiser,From a Whisper to a Scream,57.0,37.0
4523,Iko Uwais,The Raid: Redemption,481.0,316.0
4537,Ursula Andress,Dr. No,184.0,389.0
4542,Hiroshi Abe,Godzilla 2000,107.0,140.0
4592,Matthew Ziff,Hardflip,2.0,5.0
4599,Judy Greer,The Specials,29.0,54.0
4606,David Keith,In Her Line of Fire,8.0,12.0
4649,Dwayne Johnson,Snitch,238.0,122.0
4672,Corbin Allred,Saints and Soldiers,33.0,157.0
4676,Tina Fey,Aqua Teen Hunger Force Colon Movie Film for Th...,82.0,73.0
4694,Naomi Watts,King Kong,446.0,2618.0
4710,Stacy Keach,Mercy Streets,15.0,16.0
4747,Takashi Shimura,Seven Samurai,153.0,596.0
4776,Elizabeth Streb,Born to Fly: Elizabeth Streb vs. Gravity,10.0,10.0
4817,Michael Dudikoff,American Ninja 2: The Confrontation,40.0,46.0
4828,Viggo Mortensen,The Prophecy,56.0,194.0
4897,Clint Eastwood,A Fistful of Dollars,122.0,235.0
5012,Mireille Enos,Sabotage,233.0,212.0
5035,Carlos Gallardo,El Mariachi,56.0,130.0
97,Leonardo DiCaprio,Inception,642.0,2803.0
641,Leonardo DiCaprio,Body of Lies,238.0,263.0
1422,Leonardo DiCaprio,The Man in the Iron Mask,83.0,244.0
1560,Leonardo DiCaprio,The Quick and the Dead,63.0,216.0
255,Brad Pitt,Mr. & Mrs. Smith,233.0,798.0
382,Brad Pitt,Spy Game,142.0,361.0
470,Brad Pitt,Fury,406.0,701.0
2898,Brad Pitt,True Romance,122.0,460.0

In [56]:
# Write your code for grouping the combined dataframe here
Actor_name=Combined.groupby('actor_1_name')
Actor_name

In [57]:
#Mean critic Review and Mean audience review grouped by the actor's name in above combined data frame
#Using pivot to grorup by both and then get sorted mean.
Critic_reviews=Actor_name['num_critic_for_reviews'].mean().sort_values(ascending=False)
Critic_reviews

actor_1_name
Albert Finney           750.000000
Peter Capaldi           654.000000
Bryce Dallas Howard     644.000000
Benedict Cumberbatch    590.000000
Charlie Hunnam          575.000000
Emma Stone              547.000000
Iko Uwais               481.000000
Jennifer Lawrence       478.333333
Edgar Arreola           478.000000
Sharlto Copley          472.000000
Chris Hemsworth         468.272727
Ed Begley Jr.           464.000000
Daryl Sabara            462.000000
Mike Vogel              459.000000
Robert Downey Jr.       452.571429
Matt Frewer             451.000000
Elizabeth McGovern      447.000000
Toby Jones              440.000000
Bradley Cooper          439.666667
Tom Hardy               434.800000
Wood Harris             432.000000
Michael Smiley          427.000000
Jessica Barden          417.000000
Ryan Gosling            415.000000
Giancarlo Giannini      403.000000
John Boyega             399.000000
Zack Ward               396.000000
Anna Kendrick           393.000000
Eva Green               388.666667
Christoph Waltz         386.250000
                           ...
Corbin Allred            33.000000
Paul Hogan               32.000000
M. Emmet Walsh           32.000000
Cheech Marin             31.000000
Sarunyu Wongkrachang     31.000000
Wanda Sykes              31.000000
Rapulana Seiphemo        30.000000
Lara Jill Miller         29.000000
Cliff Robertson          27.000000
Brian Bosworth           27.000000
Hulk Hogan               27.000000
Wesley Jonathan          25.000000
Kieran Culkin            25.000000
Jason Robards            25.000000
Sam Waterston            24.000000
Marley Shelton           24.000000
Eddie Izzard             19.000000
Burt Young               19.000000
Antoni Corone            17.000000
Michael Berryman         17.000000
Stacy Keach              15.000000
Rosanna Arquette         13.000000
Elizabeth Streb          10.000000
Tom Berenger             10.000000
Diahann Carroll           9.000000
Esai Morales              9.000000
David Keith               8.000000
Jada Pinkett Smith        8.000000
Kevin Pollak              5.000000
Matthew Ziff              2.000000
Name: num_critic_for_reviews, Length: 486, dtype: float64

**Checkpoint 6:** `Leonardo` has aced both the lists!